# -*- coding: utf-8 -*-
"""DL Prgm2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnZrEaWk-AgpFlwOShYxyY1oKB8zOFSA
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense , Input
from tensorflow.keras.optimizers import SGD

model = Sequential ([Input(shape =(2,)) ,
                    Dense(16 , activation ='relu'),
                    Dense(16 , activation ='relu'),
                    Dense(1 , activation ='sigmoid') ])
model.compile(loss = 'binary_crossentropy',
              optimizer = SGD( learning_rate=0.5) , metrics=['accuracy'])


# Batch Gradient Descent → use the whole dataset as one batch
model.fit(X, y, epochs=200 , batch_size=len(X), verbose=0)

# Stochastic / mini - batch → small batch size , many updates per epoch
model.fit(X, y, epochs=200 , batch_size =16, verbose=0)