# -*- coding: utf-8 -*-
"""DL Prgm3.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JCSsVE-6VPigiV9xQfKedcKzeOkFc8rq
"""

import tensorflow as tf
from tensorflow. keras import datasets, layers, models
import matplotlib. pyplot as plt

# Load the MNIST dataset
(train_images, train_labels), (test_images, test_labels) = datasets.mnist. load_data ()

# Preprocess the data
# Reshape the dataset to include a channel dimension (needed for CNN)
train_images = train_images.reshape((train_images. shape [0], 28, 28, 1))
test_images = test_images.reshape((test_images. shape [0], 28, 28, 1))

# Normalize the pimel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

# Define the CNN model
model = models. Sequential ([
layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28,
1)),
layers. MaxPooling2D((2,2)),
layers.Conv2D(64, (3, 3), activation='relu'),
layers. MaxPooling2D((2, 2)),
layers.Conv2D(64, (3, 3), activation='relu'),
layers. Flatten (),
layers. Dense (64, activation='relu'),
layers. Dense (10, activation='softmax')

])

# Compile the model
model.compile (optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

# Train the model
history = model. fit(train_images, train_labels, epochs=5,
validation_data=(test_images, test_labels))

# Evaluate the model on test data
test_loss, test_acc = model. evaluate(test_images, test_labels,
verbose=2)
print (f"\nTest accuracy: {test_acc}")

# Plot training history (accuracy & loss)
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt . plot (history . history ['accuracy'], label='Training Accuracy')
plt . plot (history . history ['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch'); plt.ylabel ('Accuracy') ; plt. legend (loc='lower right')
plt.title('Training and Validation Accuracy')
plt.subplot(1, 2, 2)
plt . plot (history . history ['loss'], label='Training Loss')
plt .plot (history . history ['val_loss'], label='Validation Loss')
plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.legend (loc='upper right')
plt.title('Training and Validation Loss')
plt.show()